### ISSUE TITLE
I tried many many times but still can't make it work for "Authentication failed", do U have any idea?

### ISSUE THREAD

**Issue by swif2** [biomadeira/jasper#9]
Here is the errror log from Travis-CI:

git push --quiet origin master
remote: Invalid username or password.
fatal: Authentication failed for 'https://wenzhishen:My_Travis_Profile_Token@github.com/wenzhishen/wenzhishen.github.io.git/'
rake aborted!
Command failed with status (128): [git push --quiet origin master...]

My repository is at:
https://github.com/wenzhishen/wenzhishen.github.io
Environment Variables GIT_EMAIL & GIT_USERNAME is correct. I have checked twice. The TOKEN is copied from Travis-CI profile.
Can you find something incorrect in my configurations? I have no idea what to do now.
Thanks!

**Comment by biomadeira** [comment]
Hi @wenzhishen 

I am not sure what the problem is but just to double check... did you generate a token from your github account and encrypted it with the travis gem as described in the .travis.yml?

```
# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN="YOUR_TOKEN'
env:
  global:
    secure: "b72o3XVEGn9YATKTZxRJgd61dCpZMgXaxUKiOMFNLj+6Wl+ff9lOUCyEOd1TP//DV6KdHPtJKg6Ryua0tzJ7h7d/DpIPWg/S0nGXr9n+Wfw9L2V+p0mEIiDH1LVD1qnEq86+gTmLjXIwtnYhiyrWhtnIo+nW/IGFsp30q9sL5GLM1U2I/tdEZ91WhXdXojUPQyVHiAGoyHzl4LFYq7jrAQJhbejvwfeJLcvbZlpx8swptvJ1L1swJ2HcwtVzE8c/2tcGcaj/D5IunEqMC9T4Ig8qW0G52AQhNipkRPoetX9f15h2n2O8WjoveTku+H6CI2t/HfMP4D51hSyHmt6VtoImeF6YwQiEaoKt8JUD/j+CM55vG2No69/xMM5WmGfXCQfabw6+e2ioQCjBDASUm6JEbiIJnqaF20AM9fW0L5grAHHRp0YTjhxfNj7c+FTq5KuU/imVlTnK613t1f7BHxtLgY27NR5/6hGTU1p0zf3gyFvlzhm1n/2MeFpDbsjuG3VHc3lxtcGm2dZIRDXSOBMibUoOa8HewQxJfZ5edIGD74GQprH41idcvJeoA9pG8mEUFf+F2KXJUew6+KO+do+00gmALgqLnjm+JGKr5hWuMWz78zDp44qIHGgIWNemEaishNvj6Xyg9f8ryuxbiYEtsSaSzeKQln7BjrD2/fs="
```

If you did this right then it should work strait away...
